# Generated by Django 5.2.3 on 2025-07-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="views_count",
            new_name="views",
        ),
    ]
