# Generated by Django 5.2.3 on 2025-08-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_content_alter_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [("can_manage_blog", "Может управлять содержимым блога")]
            },
        ),
    ]
